import { GoogleGenerativeAI } from '@google/generative-ai';
import { env } from '../config/env';
import { AppError } from '../middleware/errorHandler';
import { QnaChunk } from '../types';
import { logger } from '../utils/logger';

let client: GoogleGenerativeAI | null = null;

export interface ConversationTurn {
  question: string;
  answer:   string;
}

function getClient(): GoogleGenerativeAI {
  if (!env.GEMINI_API_KEY) {
    throw new AppError('GEMINI_API_KEY is not configured. Please add it to your .env file.', 500);
  }
  if (!client) {
    client = new GoogleGenerativeAI(env.GEMINI_API_KEY);
  }
  return client;
}

function buildContext(chunks: QnaChunk[]): string {
  return chunks
    .map(c => {
      const timestamp = c.start_time ? `Timestamp: ${c.start_time} - ${c.end_time ?? ''}` : '';
      return `[Lecture Content]
Topic: ${c.topic ?? 'General'}
Q: ${c.question}
A: ${c.answer}
${timestamp}`.trim();
    })
    .join('\n\n');
}

function buildHistoryBlock(turns: ConversationTurn[]): string {
  if (turns.length === 0) return '';
  const lines = turns.flatMap(t => [`Student: ${t.question}`, `AI Tutor: ${t.answer}`]);
  return `Conversation history (for context only — do not repeat unless directly relevant):\n${lines.join('\n')}\n`;
}

const SYSTEM_PROMPT = `You are a lecture-specific AI tutor for the course "Master Prompt Engineering with ChatGPT".
Answer the student's question using ONLY the provided lecture Q&A context.

Rules:
1. Use ONLY the provided context. Do NOT use outside knowledge.
2. If the answer is not in the context, respond: "I could not find this information in this lecture."
3. Explain in simple, student-friendly language.
4. Do NOT invent or guess information not present in the context.
5. Do NOT mention "Source 1", "Source 2", or any source/citation labels in your answer.
6. Do NOT include timestamps (e.g. "Timestamp: 7:09 - 8:40") in your answer — they are shown separately in the UI.
7. Keep answers concise and educational.
8. If the student asks a follow-up (e.g. "can you explain more?"), use the conversation history to understand what they are referring to.`;

const sleep = (ms: number) => new Promise(res => setTimeout(res, ms));

const LLM_FALLBACK_SYSTEM_PROMPT = `You are an AI tutor assistant. The student asked a question that was not found in the current lecture's content.

Rules:
1. If the question is a valid educational or general-knowledge question, answer it using your own knowledge.
2. End your answer with exactly this line on a new paragraph: "⚠️ Note: This answer was generated by the AI model and is not sourced from the lecture content."
3. If the question is completely irrelevant, nonsensical, or unrelated to any educational topic, respond only with: "This topic does not appear to be covered in this current lecture."
4. Keep the answer concise and student-friendly.`;

export const generateAnswerFromLLM = async (
  question: string,
  lectureTitle: string,
  attempt = 1
): Promise<string> => {
  const genAI = getClient();
  const modelName = attempt <= 2 ? 'gemini-2.5-flash' : 'gemini-1.5-flash';
  const model = genAI.getGenerativeModel({
    model: modelName,
    generationConfig: {
      temperature: 0.5,
      maxOutputTokens: 4096,
    },
  });

  const prompt = `${LLM_FALLBACK_SYSTEM_PROMPT}

Lecture: "${lectureTitle}"

Student Question: ${question}`;

  logger.info(`[LLM] 🤖 No lecture chunks — generating from general knowledge: "${question.slice(0, 60)}..."`);

  try {
    const result = await model.generateContent(prompt);
    const answer = result.response.text();
    if (!answer?.trim()) throw new AppError('Empty response from AI model', 500);
    logger.info(`[LLM] ✅ LLM fallback answer generated (${answer.length} chars)`);
    return answer;
  } catch (err: unknown) {
    const msg = String((err as Error).message ?? '');
    const isRateLimit  = msg.includes('429') || msg.toLowerCase().includes('quota') || msg.toLowerCase().includes('resource_exhausted');
    const isOverloaded = msg.includes('503') || msg.toLowerCase().includes('service unavailable');

    if ((isRateLimit || isOverloaded) && attempt <= 3) {
      const wait = Math.pow(2, attempt) * 3000;
      await sleep(wait);
      return generateAnswerFromLLM(question, lectureTitle, attempt + 1);
    }

    if (err instanceof AppError) throw err;
    logger.error('[LLM] ❌ LLM fallback error:', err);
    throw new AppError('AI model failed to generate a response. Please try again.', 500);
  }
};

export const generateAnswer = async (
  question: string,
  chunks: QnaChunk[],
  lectureTitle: string,
  history: ConversationTurn[] = [],
  attempt = 1
): Promise<string> => {
  const genAI = getClient();
  // Fall back to stable 1.5-flash after 2 failed attempts on 2.5-flash
  const modelName = attempt <= 2 ? 'gemini-2.5-flash' : 'gemini-1.5-flash';
  const model = genAI.getGenerativeModel({
    model: modelName,
    generationConfig: {
      temperature: 0.3,
      maxOutputTokens: 8192,
    },
  });

  const context     = buildContext(chunks);
  const historyBlock = buildHistoryBlock(history);
  const prompt = `${SYSTEM_PROMPT}

Lecture: "${lectureTitle}"

Lecture Q&A Context:
${context}
${historyBlock ? `\n${historyBlock}` : ''}
Current Student Question:
${question}`;

  logger.info(`[LLM] 🤖 Sending prompt to Gemini (${chunks.length} chunks, question="${question.slice(0, 60)}...")`);

  try {
    const result = await model.generateContent(prompt);
    const finishReason = result.response.candidates?.[0]?.finishReason;

    if (finishReason === 'MAX_TOKENS') {
      logger.warn('[LLM] ⚠️  Response hit MAX_TOKENS — answer may be truncated');
    }

    const answer = result.response.text();
    if (!answer?.trim()) {
      throw new AppError('Empty response from AI model', 500);
    }

    logger.info(`[LLM] ✅ Gemini answered (${answer.length} chars, finish=${finishReason})`);
    return answer;
  } catch (err: unknown) {
    const msg = String((err as Error).message ?? '');
    const isRateLimit  = msg.includes('429') || msg.toLowerCase().includes('quota') || msg.toLowerCase().includes('resource_exhausted');
    const isOverloaded = msg.includes('503') || msg.toLowerCase().includes('service unavailable') || msg.toLowerCase().includes('high demand');

    if ((isRateLimit || isOverloaded) && attempt <= 3) {
      const wait = Math.pow(2, attempt) * 3000; // 6s, 12s, 24s
      const fallbackNote = attempt >= 2 ? ' (switching to gemini-1.5-flash)' : '';
      logger.warn(`[LLM] Transient error on attempt ${attempt}/3${fallbackNote} — retrying in ${wait / 1000}s...`);
      await sleep(wait);
      return generateAnswer(question, chunks, lectureTitle, history, attempt + 1);
    }

    if (err instanceof AppError) throw err;
    logger.error('[LLM] ❌ Gemini error:', err);
    throw new AppError('AI model failed to generate a response. Please try again.', 500);
  }
};
